### ISSUE TITLE
The Gemfile specifies faraday ~> 0.9, but the :api_debug seems to require 0.9.1

### ISSUE THREAD

**Issue by kjhenner** [jarthod/survey-gizmo-ruby#58]
Using version Faraday version 0.9.0 gives me the following error. Updating to 0.9.1 resolves it.
https://github.com/lostisland/faraday/commit/fb6ed87714e4b3fbf2c846032ce62617ed57bfe8
```
=> {:user=>"my_username", :password=>"my_password", :api_url=>"https://restapi.surveygizmo.com", :api_version=>"4", :api_debug=>true}
>> survey = SurveyGizmo::API::Survey.first(id: my_survey's_id)
ArgumentError: wrong number of arguments (3 for 1..2)
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/response/logger.rb:7:in `initialize'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/middleware.rb:21:in `new'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/middleware.rb:21:in `new'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:48:in `build'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:162:in `block in to_app'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:162:in `each'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:162:in `inject'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:162:in `to_app'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:152:in `app'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/survey-gizmo-ruby-5.0.3/lib/survey_gizmo/connection.rb:8:in `get'
        from /Users/Henner/.rvm/gems/ruby-2.0.0-p451/gems/survey-gizmo-ruby-5.0.3/lib/survey_gizmo/resource.rb:65:in `first'
        from (irb):5
        from /Users/Henner/.rvm/rubies/ruby-2.0.0-p451/bin/irb:12:in `<main>'
```

**Comment by apurvis** [comment]
faraday is in violation of like every best practice of semantic versioning so this doesn't surprise me.
locally i actually use and test with faraday 0.9.2 so i will probably lock the gem to that version.

**Comment by kjhenner** [comment]
Cool, sounds good.

**Comment by apurvis** [comment]
fixed in PR https://github.com/jarthod/survey-gizmo-ruby/pull/59
